# lappsgrid/jupyter-lsd-kernel

FROM jupyter/minimal-notebook
MAINTAINER Keith Suderman (suderman@cs.vassar.edu)

USER root

RUN mkdir -p /jupyter/lsd
RUN cp ./jupyter-lsd-kernel-1.0.0-SNAPSHOT.jar /jupyter
RUN cp kernel.json /jupyter/lsd


